### ISSUE TITLE
1.1.0 package does not have lib folder?

### ISSUE THREAD

**Issue by canadaduane** [react-designer/react-designer#39]
Not sure if this is the cause of my trouble, but when using `1.1.0` in a project, I can't seem to import it. I think it may be missing the transpiled `lib` folder.

```
import React from 'react'
import Designer, { Path } from 'react-designer'
```

results in:

`Error: Cannot find module 'react-designer'`

**Comment by othree** [comment]
Might caused by #37 
Need manually run `npm run prepare` before publish.

**Comment by hartatovich** [comment]
same problem , cannot import module
